apiVersion: v1
kind: Pod
metadata:
  name: mavenpod
  namespace: test-ns
  labels:
    app: mavenapp
spec:
  containers:
    - name: mavencontainer
      image: ankush3891/mv-web-app:1
      ports:
        - containerPort: 8080
