apiVersion: v1
kind: Pod
metadata:
   name: staticpod
   labels:
     app: javaapp
spec:
   containers:
      - name: javastaticpod
        image: ankush3891/java-web-app:3
        ports:
          - containerPort: 8080
